language: node_js
sudo: false # defaults to sending build to container-based infrastructure on Travis

node_js:
  - '0.10'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c9dc628573cc153706fa
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:
  matrix:
    - JOB=unit
   # - JOB=e2e
  global:
    - SAUCE_USERNAME=cerdman
    - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-build/logs
    - secure: u1LMU8PhwOtLO5Jnk818SqREQWmhUL1kxCZedEkV7qqeSg77kaMn7Xg5tMhQsa7ijpk/3qMaYodXXB8dDT0q/0anNcDp6eN1vFv+ZN9Vk8dzSpUPB/YP0XH2HSDOvkyrgmD36LPiWk46pmrfJ25Eo0Cg3tYloRIEdjAchJ8OpWOSrT2ZE9qOzycqOZKX9qFcKGDvkM7jTa/pMppWqAgO3LDNzJOGKSMFOYMX6TMu8ye2NyrsG36FjhhK6SZ+2vDESGEdP/BF336yJtkq8gJvIM4+8y/yveeE8wA6gLX/4Z98jTCmynCqwDajzuKq7zO4cnqlEEqQcewJLIrHKWpK/+cjBXa7+CR10cMah0hW2o4w/IPGJjQPz0JFfpcwfGgpRJ6qlDzSddu1zK9EfVqciRJiHc0zcGEml8kFwhAGZt1Xveeq2iKzqsb5JGe1aaSyWhOSTwYnpygEjfXWY+SAIQFloaX7i1w22V+2MPyE+yHlHWf/2gkDwoxJQ8wPXj+pLqhpTaBZHNLMvCHf0lWuqqv2Cdt36daOHMolitGa11WWjL4kfZivUgCjlkDF80OIUJ3ADroIt3F+HSVS6UA9eGTM9VK7oIUBj/ec2x1hYm1NVTVf6Xr4W9vCD310w3Hgl4Znm6RkKy6QZjBnW5jOi4ffNxXXsEKYn/j977uUbR4=

branches:
  only:
    - master
    - /^3\.0$/
    - /^release-.*$/

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm config set spin false

before_script:
  - git fetch --tags
  - chmod +x ./lib/sauce/sauce_connect_setup.sh ./lib/sauce/sauce_connect_block.sh ./travis_build.sh ./travis_print_logs.sh
  - mkdir -p $LOGS_DIR
  - ./lib/sauce/sauce_connect_setup.sh
  - npm install --quiet -g grunt-cli karma-cli
  - npm install
  - bower install
  - grunt install
  - ./lib/sauce/sauce_connect_block.sh

script:
  - ./travis_build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && grunt release

after_failure:
  - ./travis_print_logs.sh

after_script:
  - ./travis_print_logs.sh
